CREATE TABLE `得点管理システム` (
	`NO` VARCHAR(10) COMMENT 'サンプルデータ：2231111',
	`NAME` VARCHAR(10) DEFAULT NULL COMMENT 'サンプルデータ：大原太郎',
	`ENT_YEAR` INT(10) DEFAULT NULL COMMENT 'サンプルデータ：2023',
	`CLASS_NUM` CHAR(3) DEFAULT NULL COMMENT 'サンプルデータ：131',
	`IS_ATTEND` BOOLEAN DEFAULT NULL COMMENT 'サンプルデータ：TRUE（在学中）、FALSE（退学済み）',
	`SCHOOL_CD` CHAR(3) DEFAULT NULL COMMENT 'サンプルデータ：oom',
	PRIMARY KEY (`NO`)
) ENGINE=InnoDB;